#!/bin/bash 

myname=scripts/$(basename $0)
mydir=$(cd $(dirname $0);pwd)

source $mydir/../include/misc.sh

filename=${1-}
[[ "" = "$filename" ]] && ErrorExit "No filename given" 3

defaultextract=false
extensions=(.zip)

for ext in "${extensions[@]}" ; do	
     [[ ${filename} == *$ext ]] && {
     	defaultextract=true
	break
     }
     [[ -f $filename${ext} ]] && {
     	defaultextract=true
	break
     }
done

[[ $defaultextract ==  true ]] && {
	newname=$(echo $filename | sed -e "s/${ext}$//")
	echo "$0: File uncompressed new name is $newname"
	gunzip $filename
	exit $?
}

outname=${filename}.out.$$
trap "rm -f $outname" 1 2 3 15

[[ -f $outname ]] && {
	rm -f $outname
	[[ $? != 0 ]] && ErrorExit "Cannot remove file $outname (tmpfile)" 4
}


gunzip -p < $filename > $outname
status=$?
[[ $status !=  0 ]] && ErrorExit "zip failed" $status

mv $outname $filename
status=$?
[[ $status != 0 ]] && ErrorExit "moving $outname to $filename failed" $status

exit 0



