---
- name: Deploy Docker Compose Application
  hosts: your_servers
  become: true
  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file to the server
      copy:
        src: docker-compose.yml
        dest: /opt/docker-compose/docker-compose.yml

    - name: Ensure docker-compose up
      command: docker-compose up -d
      args:
        chdir: /opt/docker-compose
